package com.tiffany.model;

/**
 * Author: Jane
 */

import java.util.*;
import javax.persistence.*;


/**
 * Screeningprogram generated by hbm2java
 */
@Entity
@Table(name="screeningprogram"
, uniqueConstraints = {  }
)

public class ScreeningProgram  implements java.io.Serializable {


    // Fields

     private Long id;
     private Date startDate;
     private char complete;
     private Long username;

    // Constructors

    /** default constructor */
    public ScreeningProgram() {
    }

	/** minimal constructor */
    public ScreeningProgram(Long id, Date startDate, char complete) {
        this.id = id;
        this.startDate = startDate;
        this.complete = complete;
    }

    /** full constructor */
    public ScreeningProgram(Long id, Date startDate, char complete, Long username) {
        this.id = id;
        this.startDate = startDate;
        this.complete = complete;
        this.username = username;
    }



    // Property accessors
    @Id @GeneratedValue(strategy=GenerationType.AUTO)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    @Column(nullable=false)
    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    @Column(nullable=false)
    public char getComplete() {
        return this.complete;
    }

    public void setComplete(char complete) {
        this.complete = complete;
    }
    @Column(nullable=true)
    public Long getUsername() {
        return this.username;
    }

    public void setUsername(Long username) {
        this.username = username;
    }

}