<%@ include file="/common/taglibs.jsp"%>

<head>
    <title>Help</title>
    <meta name ="keywords" content ="Add sampler, Add water body, Update contractor, update sampler, update water body, assign sampler"/>
  <style type="text/css"><!--
.featurenav {  font-size: 11px; font-family: Arial, Helvetica, sans-serif; text-decoration: none; color: #269ABF}
a.featurenav:link {  text-decoration: none}
a.featurenav:hover {  text-decoration: underline}
a.featurenav:visited {  color: #999999}

--></STYLE>
     
 
</head>

<body id="help">


<a href="mouseover.html" onMouseOver="hiLite('a','a2','Your Comment Here')" onMouseOut="hiLite('a','a1','')"><img name="a" src="a1.jpg" border=0 width=107 height=36></a>
<br>
<br>
<p><b>Help!This page should help you to use TiGERS.</b></p>

<h1>Welcome to the Help Page</h1>
<p>As an environmental officer you can add information of contractor, water bodies and related exceedance values, samplers and their screening frequencies. <br>
You will also be able to view media files taken during the execution of a screening program and added to the samplers by contractors. <br>
 The system will allow you to request individual analysis of screening programs to be performed by contractors via email. <br>
  The reports and graphs of parameter values and exceedance values of samplers within a specified date range are able to be generated by the system. </p>
<ul>
<li><a href="AddSampler.jsp">To Add Sampler</a></li>
<li><a href="AddWaterBody.jsp">To Add Water Body</a></li>
<li><a href="UpdateContractor.jsp">To Update Contractor</a></li>
<li><a href="UpdateSampler.jsp">To Update Sampler</a></li>
<li><a href="UpdateWaterBody.jsp">To Update Water Body</a></li>
<li><a href="AssignSampler.jsp">To Assign Sampler to Contractor</a></li>
<li><a href="EnterSamplingFrequencies.jsp">To Enter Sampling Frequencies</a></li>
<li><a href="ManageExceedanceValues.jsp">To Manage Exceedance Values</a></li>
<li><a href="SelectSamplingLocation.jsp">To Select Sampling Location</a></li>
<li><a href="PerformScreeningProgram.jsp">To Perform Screening Program</a></li>
<li><a href="ScheduleSamplingFrequencies.jsp">To Schedule Sampling Frequencies</a></li>
<li><a href="CreateEnvironmentalAuditReport.jsp">To Create Environmental Report</a></li>
<li><a href="Glossary.jsp">Glossary</a></li>
<li><a href="Definitions.jsp">Definitions</a></li>
</ul>
<br/> 
<table border="0" width="700" cellpadding="0" cellspacing="0">
        <tr> 
          <td class="featurenav" align="center" bgcolor="#3366CC"><strong>
          
          	<a href="AddSampler.jsp" class="featurenav"><font color="#FFFFFF">Add Sampler</font></a> | 
            <a href="AddWaterBody.jsp" class="featurenav"> <font color="#FFFFFF">Add Water Body</font></a>|
            <a href="UpdateContractor.jsp" class="featurenav" ><font color="#FFFFFF">Update Contractor</font></a> |
         	<a href="UpdateSampler.jsp" class="featurenav" >  <font color="#FFFFFF">Update Sampler</font></a> |
            <a href="UpdateWaterBody.jsp" class="featurenav"><font color="#FFFFFF">Update Water Body</font></a> |
           <a href="AssignSampler.jsp" class="featurenav"> <font color="#FFFFFF">Assign Sampler</font></a>|
            <a href="EnterSamplingFrequencies.jsp" class="featurenav"><font color="#FFFFFF">Enter Frequencies</font></a>|
           <a href="ManageExceedanceValues.jsp" class="featurenav" > <font color="#FFFFFF">Manage Exceedance</font></a> |
            <a href="SelectSamplingLocation.jsp" class="featurenav"><font color="#FFFFFF">Select Location</font></a> |
           <a href="PerformScreeningProgram.jsp" class="featurenav"> <font color="#FFFFFF">Perform Screening</font></a>|
            <a href="ScheduleSamplingFrequencies.jsp" class="featurenav"><font color="#FFFFFF">Schedule Frequencies</font></a>|
            <a href="CreateEnvironmentalAuditReport.jsp" class="featurenav"><font color="#FFFFFF">Create Environmental Report</font></a> |
           <a href="CreateExceedanceReport.jsp" class="featurenav"> <font color="#FFFFFF">Create Exceedance Report</font></a> |
            <a href="Glossary.jsp" class="featurenav"><font color="#FFFFFF">Glossary</font></a>|
           <a href="Definitions.jsp" class="featurenav"> <font color="#FFFFFF">Definitions</font></a>| 
           <a href="Keywords.jsp" class="featurenav"> <font color="#FFFFFF">Search</font></a>|                              
           </strong></td>
        </tr>
</table>
</body> 



 

<%-- 
<%








<head>
<title>To Add Sampler</title>
</head>
<body>
<h1>To Add Sampler</h1>
<ol>
<li>Choose the Add New Sampler option.</li>
<li>Enter the unique alphanumeric ID</li>
<li>Enter a location either as a latitude/longitude pair or as a klm file via the Google Earth user interface.</li>
<li>Select the Water Body containing the Sampler.</li>
<li>Enter the frequencies that water samples will be taken.  If the sampler is for a ground water body, then a licence number needs to be entered.</li>
<li>Enter a monitoring purpose description.</li>
<li>Click the confirm button to confirm the addition of the new Sampler to the database.</li>
</ol>
<p>If any of the entered values are invalid, an error message will be displayed and the sampler will not be added until the errors are corrected. </p>
<a href="HelpPage.html">Return to Help Page</a>
</body>


<head>
<title>Add Water Body</title>
</head>
<body>
<h1>To Add Water Body</h1>
<ol>
<li>Choose the Add New Water Body option.</li>
<li>Enter the unique name.</li>
<li>Select surface water (a creek or river)or ground water (an aquifer).</li>
<li>Enter the exceedance limits for the parameters to be analysed.</li>
<li>Click the confirm button to confirm the addition to the database.</li>
</ol>
<p>if any of the entered values are invalid, an error message will be displayed and the Water Body will not be added until the errors are corrected.
<a href="HelpPage.html">Return to Help Page</a>
</body>

<head>
<title>To Update Contractor</title>
</head>
<body>
<h1>To Update Contractor</h1>
<ol>
<li>Choose the Update Contractor option.</li>
<li>Select the contractor you wish to update.  Any of the Contractor names, contact names, telephone numbers and email addresses may be amended.</li>
<li>Click the confirm button to confirm the update and update the database.  You can choose not to save the changes by not confirming the update.</li>
</ol>
<a href="HelpPage.html">Return to Help Page</a>
</body>


<head>
<title>To Update Sampler</title>
</head>
<body>
<h1>To Update Sampler</h1>
<ol>
<li>Choose the Update Sampler option.</li>
<li>Choose the Sampler you want to change.</li>
<li>Delete a Sampler providing that no Sample data has been added for that Sampler yet.</li>
<li>The location can be changed either by entering a latitude/longitude pair or as a kml file via the Google Earth user interface. 
 <br>The licence number, sampling frequencies and monitoring purpose description may be edited.</li>
<li>Click the confirm button to confirm the update and update the database.</li>
</ol>
<p>If any of the entered values are invalid, an error message will be displayed and the sampler will not be added until errors are corrected. <br>
When a Sampler is deleted, it is removed entirely and does not show up on maps.</p>
<a href="HelpPage.html">Return to Help Page</a>
</body>


<head>
<title>To Update Water Body</title>
</head>
<body>
<h1>To Update Water Body</h1>
<ol>
<li>Choose the Update Water Body option.</li>
<li>Select the water body you want to update.</li>
<li>Edit the exceedance limits for the parameters to be analysed.</li>
<li>Click the confirm button to confirm the update and update the database.</li>
</ol>
<p>If any of the entered values are invalid, an error message will be displayed and the Water Body will not be added until the errors are corrected.</p>
<a href="HelpPage.html">Return to Help Page</a>
</body>



<head>
<title>To Assign Sampler to Contractor</title>
</head>
<body>
<h1>To Assign Sampler to Contractor</h1>
<ol>
<li>Choose the Assign Sampler to Contractor option.</li>
<li>Select a sampling location and then choose the Contractor to assign it to.</li>
<li>Click on the confirm button to confirm the assignment update to the database.</li>
</ol>
<p>If the Sampler has been previously assigned to another Contractor the assignment is removed from the old Contractor and given to the new Contractor.</p>
<a href="HelpPage.html">Return to Help Page</a>
</body>


<head>
<title>To Enter Sampling Frequencies</title>
</head>
<body>
<h1>To Enter Sampling Frequencies</h1>
<ol>
<li>Select a subset of parameters which may be tested at this location.</li>
<li>Enter the frequency at which these parameters will be screened. <br>
Frequency is one of daily, weekly, fortnightly, monthly, half yearly and yearly.</li>
<li>Enter a comprehensive screening frequency which is when all parameters will be screened. <br>
If Sampler is for a ground Water Body then a depth monitoring frequency is entered.</li>
</ol>
<p>All frequencies will be entered for a new Sampler, but any subset of frequencies may be amended</p>
<a href="HelpPage.html">Return to Help Page</a>
</body>


<head>
<title>To Manage Exceedance Values</title>
</head>
<body>
<h1>To Manage Exceedance Values</h1>
<p>Managing Exceedance Values involves adding or updating Water Body information</p>
<ol>
<li>Set both the minimum and the maximum exceedance value for PH.</li>
<li>Set both the minimum and the maximum exceedance value for the electrical conductivity.</li>
<li>Set both the minimum and the maximum exceedance value for the temperature.</li>
<li>Set both the minimum and the maximum exceedance value for arsenic. </li>
<li>Set both the minimum and the maximum exceedance value for oil and grease.</li>
<li>If the Water Body is ground water set both the minimum and the maximum exceedance value for depth to collar.</li>
<li>If the Water Body is surface water set both the minimum and the maximum exceedance value for fluoride.</li>
<li>If the Water Body is surface water set both the minimum and the maximum exceedance value for chromium.</li>
<li>Click the confirm button to confirm the addition of the update to the database.</li>
</ol>
<p>All exceedance values will be entered for a new Water Body, but any subset of exceedances may be amended.</p>
<a href="HelpPage.html">Return to Help Page</a>
</body>



<head>
<title>To Select Sampling Location</title>
</head>
<body>
<h1>To Select Sampling Location</h1>
<ol>
<li>Select a Sampler by clicking on its location map or by selecting it from a list of Sampler locations.</li>
</ol>
<a href="HelpPage.html">Return to Help Page</a>
</body>



<head>
<title>To Perform Screening Program</title>
</head>
<body>
<h1>To Perform Screening Program</h1>
<ol>
<li>Choose the Start New Screening Program option.</li>
<li>Select the Water Body.</li>
<li>Select the sampling location on the map.</li>
<li>View the sampling frequencies.  Any Parameters which need sampling are then added to the program.<br>
This is repeated for all Samplers for the Water Body.</li>
<li>Click the submit button to submit the program.<br>
An email will automatically be sent to the Contractors assigned to each Sampler, <br>
requesting them to take a Sample and listing with Parameters to be analysed.<br>
The Contractors take Samples and send them to the Laboratory assigned to each Sampler, along with Parameter details. <br>
The Contractor updates the System so that it knows a Sample has been sent. <br>
The Laboratories analyse the Samples and bulk upload the results.<br>
When all Samples have been analysed, an email is sent automatically to you, advising you that the Screening Program has been completed.</li>
</ol>
<a href="HelpPage.html">Return to Help Page</a>
</body>


<head>
<title>To Schedule Sampling Frequencies</title>
</head>
<body>
<h1>To Schedule Sampling Frequencies</h1>
<ol>
<li>Choose the Schedule of Sampling Frequencies option.</li>
<li>Select the Water Body and then choose to group the data either by<br>
Sampler/Frequency/Screening Parameter or by <br>
Sampler/Screening Parameter. A list of screening frequencies is then displayed.</li>
</ol>
<a href="HelpPage.html">Return to Help Page</a>
</body>


<head>
<title>To Create Environmental Audit Report</title>
</head>
<body>
<h1>To Create Environmental Audit Report</h1>
<ol>
<li>Choose the Create Environmental Audit Report option. <br>
A report is generated containing a table of Sample records with all parameter values <br>
grouped by Water Body and Sampler, sorted by date.</li>
<li>Select the Water Body and select parameters analysed at that body. <br>
A graph will be shown with these parameter and a horizontal line representing the <br>
exceedances applicable to each parameter.</li>
<li>Select an exceedance line and information about that exceedance will be displayed <br>
(which parameter it applies to its value.) Where a detection limit has been recorded, <br>
rather than an actual value, this will be highlighted on the report.</li>
</ol>
<a href="HelpPage.html">Return to Help Page</a>
</body>


<head>
<title>To Create Exceedance Report</title>
</head>
<body>
<h1>To Create Exceedance Report</h1>
<ol>
<li>Choose the Create Exceedance Report option.</li>
<li>Select the Sampler location from a map. <br>
The report consists of a table showing only those Samples where an exceedance was recorded for a parameter. <br>
The records will be in date order (most recent first), and will contain date, parameter whose value was exceeded, <br>
the parameter value, the exceedance and the magnitude of exceedance. Where a detection limit has been recorded,<br>
rather than an actual value, this will be highlighted on the report.</li>
</ol>
<a href="HelpPage.html">Return to Help Page</a>
</body>


<head>
<title>Glossary</title>
</head>
<body>
<h1>Glossary</h1>
<table border="1">
<tr>
<th>Term</th>
<th>Definition</th>
</tr>
<tr>
<td>Map</td>
<td>A visual representation of the mine site in the form of an aerial photo.</td>
</tr>
<tr>
<td>Sampler</td>
<td>A generic term for an observation station that is set up at a specific sampling location to allow samples to be taken.</td>
</tr>
<tr>
<td>Sampling location</td>
<td>A geographical position at the Tiffany Gold Mine defined by a latitude/longitude pair and represented by a marker on a map <br>
at which a water sample is taken at a prescribed frequency.  Samples can be taken above ground (creek, domestic water tank) 
and below ground (bore). </td>
</tr>
<tr>
<td>(Environmental)parameter</td>
<td>A numerical description of an observed property of the environment such as pH or EC.</td>
</tr>
<tr>
<td>Screening Frequency</td>
<td>The period of time between sampling events which may vary from sampler to sampler and from parameter to parameter.<br>
Frequencies are divided into screening frequency (only some parameters are analysed)and comprehensive screening frequency <br>
(all parameters are analysed.)The latter always occurs less often. </td>
</tr>
<tr>
<td>Screening Program</td>
<td>An activity in which many pre-defined sampling locations are visited to retrieve samples that have to be analysed for a set of parameters at that time. </td>
</tr>
<tr>
<td>Sampling Date</td>
<td>Date at which a water sample is taken for later analysis in a laboratory.</td>
</tr>
<tr>
<td>EC</td>
<td>Electrical conductivity measured in micro Siemens per centimetre (uS/cm, one of the many environmental parameters measure in a water sample indicaive of salinity.</td>
</tr>
<tr>
<td>.klm</td>
<td>KLM is a file format used to display geographical data in an Earth browser such as Google Earth, Google Maps.</td>
</tr>
</table>
<a href="HelpPage.html">Return to Help Page</a>
</body>

<head>
<title>Definitions</title>
</head>
<body>
<h1>Definitions</h1>
<h4>Water Body:</h4>
<p>The information of water body can be divided into two groups, ground water and surface water.  <br> 
Ground water is contained in aquifers; each aquifies may have different exceeding minimum and/or maximum limits for all parameters are monitored. <br>
Surface water bodies are creeks and rivers which also have their own exceeding minimum and/or maximum limits for monitoring. </p>
<h4>Sampler:</h4>
<p>The water samplers are identified by their alphanumeric tag(eg GW123)and have a geographical <br>
position that should be reflected on a map with the option to enter the latitude and longitude either from the keyboard or .klm files.  <br>
Samplers need to be assigned to the water body contractors monitored.</p>
<p>Ground water samplers have a licence number (eg 20BL845484)and a monitoring purpose description.  Ground water samplers also have: </p>
<ol>
<li>A screening frequency at which a defined subset of parameters is screened.</li>
<li>A comprehensive screening frequency at which time the water depth to collar is measured to calculate </li>
<li> Ground water level above sea level</li>
</ol>
<p>Surface water samplers are carrying a monitoring description and the same screening frequency <br>
information as the ground water except the depth of river or creek that the sample is taken from.  The parameters measured for ground and surface water are <br>
shown in the table below: </p>
<table border ="1">
<caption>Parameters of Ground Water and Surface Water</caption>
<tr>
<td>&nbsp;</td>
<td>Ground Water</td>
<td>Surface Water</td>
</tr>
<tr>
<td>PH</td>
<td>O</td>
<td>O</td>
</tr>
<tr>
<td>EC [uS/cm]</td>
<td>O</td>
<td>O</td>
</tr>
<tr>
<td>Temperature[ C]</td>
<td>O</td>
<td>O</td>
</tr>
<tr>
<td>Depth to collar [m]</td>
<td>O</td>
<td>X</td>
</tr>
<tr>
<td>Fluoride [mg/L]</td>
<td>X</td>
<td>O</td>
</tr>
<tr>
<td>Chromium [mg/L]</td>
<td>X</td>
<td>O</td>
</tr>
<tr>
<td>Arsenic [mg/L]</td>
<td>O</td>
<td>O</td>
</tr>
<tr>
<td>Oil</td>
<td>O</td>
<td>O</td>
</tr>
<tr>
<td>Grease [ppm]</td>
<td>O</td>
<td>O</td>
</tr>
</table>
<p>The screening frequencies are: daily, weekly, fortnightly, monthly, half yearly and yearly.</p>
<h4>Reports and Graphs</h4> 
<p>The system generates reports and graphs.  The reports are divided into two parts audit reports and exceeding <br>
value reports.  The audit reports contain a table of parameter values (column heading)collected at all dates (row heading)
grouped by sampling points for a selectable water body.  The graphs included for <br>
each water body sampler for a selectable list of parameters.  The graphs contain a horizontal line for each of the exceeding applicable to the selected parameters which are also <br>
selectable.  The exceeding value reports consist of a table generated by selecting a sampler from a map and containing the parameters, date and measured values together <br> 
with the exceedance values and the magnitude of exceedance values. <br>
All detection limits are marked as such and not presented as measured values.</p>
<a href ="HelpPage.hyml">Return to Help Page</a>


<script language="javascript">
<!-- hide script from old browsers

//detect browser:
browserName = navigator.appName;
browserVer = parseInt(navigator.appVersion);
if (browserName == "Netscape" && browserVer >= 3) browserVer = "1";
else if (browserName == "Microsoft Internet Explorer" && browserVer == 4) browserVer = "1";
else browserVer = "2";

//preload images:
if (browserVer == 1) {
a1 = new Image(107,36);
a1.src = "/images/help/above.jpg";
a2 = new Image(107,36);
a2.src = "/images/help/below.jpg";
}

//image swapping function:
function hiLite(imgDocID, imgObjName, comment) {
if (browserVer == 1) {
document.images[imgDocID].src = eval(imgObjName + ".src");
window.status = comment; return true;
}}
//end hiding -->
</script>
   
<script src="http://www.google.com/jsapi" type="text/javascript"></script>
<script type="text/javascript">
  google.load('search', '1', {language : 'en'});
  google.setOnLoadCallback(function() {
    var customSearchControl = new google.search.CustomSearchControl('008390370047389583061:42-rdgk9wwm');
    customSearchControl.setResultSetSize(google.search.Search.FILTERED_CSE_RESULTSET);
    customSearchControl.draw('cse');
  }, true);
</script>
<link rel="stylesheet" href="http://www.google.com/cse/style/look/greensky.css" type="text/css" />

      
</body>


%>
--%>





