<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Definitions</title>
<style type="text/css"><!--
.featurenav {  font-size: 11px; font-family: Arial, Helvetica, sans-serif; text-decoration: none; color: #269ABF}
a.featurenav:link {  text-decoration: none}
a.featurenav:hover {  text-decoration: underline}
a.featurenav:visited {  color: #999999}

--></STYLE>
</head>
<body>
<h1>Definitions</h1>
<h4><b>Water Body:</b></h4>
<p>The information of water body can be divided into two groups, ground water and surface water.  <br> 
Ground water is contained in aquifers; each aquifies may have different exceeding minimum and/or maximum limits for all parameters are monitored. <br>
Surface water bodies are creeks and rivers which also have their own exceeding minimum and/or maximum limits for monitoring. </p>
<h4><b>Sampler:</b></h4>
<p>The water samplers are identified by their alphanumeric tag(eg GW123)and have a geographical <br>
position that should be reflected on a map with the option to enter the latitude and longitude either from the keyboard or .klm files.  <br>
Samplers need to be assigned to the water body contractors monitored.</p>
<p>Ground water samplers have a licence number (eg 20BL845484)and a monitoring purpose description.  Ground water samplers also have: </p>
<ol>
<li>A screening frequency at which a defined subset of parameters is screened.</li>
<li>A comprehensive screening frequency at which time the water depth to collar is measured to calculate </li>
<li> Ground water level above sea level</li>
</ol>
<p>Surface water samplers are carrying a monitoring description and the same screening frequency <br>
information as the ground water except the depth of river or creek that the sample is taken from.  The parameters measured for ground and surface water are <br>
shown in the table below: </p>
<table border ="1">
<caption>Parameters of Ground Water and Surface Water</caption>
<tr>
<td>&nbsp;</td>
<td>Ground Water</td>
<td>Surface Water</td>
</tr>
<tr>
<td>pH</td>
<td>O</td> 
<td>O</td>
</tr>
<tr>
<td>EC [µS/cm]</td>
<td>O</td>
<td>O</td>
</tr>
<tr>
<td>Temperature[ C]</td>
<td>O</td>
<td>O</td>
</tr>
<tr>
<td>Depth to collar [m]</td>
<td>O</td>
<td>X</td>
</tr>
<tr>
<td>Fluoride [mg/L]</td>
<td>X</td>
<td>O</td>
</tr>
<tr>
<td>Chromium [mg/L]</td>
<td>X</td>
<td>O</td>
</tr>
<tr>
<td>Arsenic [mg/L]</td>
<td>O</td>
<td>O</td>
</tr>
<tr>
<td>Oil</td>
<td>O</td>
<td>O</td>
</tr>
<tr>
<td>Grease [ppm]</td>
<td>O</td>
<td>O</td>
</tr>
</table> 
<p>The screening frequencies are: daily, weekly, fortnightly, monthly, half yearly and yearly.</p>
<h4><b>Reports and Graphs</b></h4> 
<p>The system generates reports and graphs.  The reports are divided into two parts audit reports and exceeding <br>
value reports.  The audit reports contain a table of parameter values (column heading)collected at all dates (row heading)
grouped by sampling points for a selectable water body.  The graphs included for <br>
each water body sampler for a selectable list of parameters.  The graphs contain a horizontal line for each of the exceeding applicable to the selected parameters which are also <br>
selectable.  The exceeding value reports consist of a table generated by selecting a sampler from a map and containing the parameters, date and measured values together <br> 
with the exceedance values and the magnitude of exceedance values. <br>
All detection limits are marked as such and not presented as measured values.</p>
<a href="index.jsp">Return to Help Page</a>
<br/><br/> 
<table border="0" width="700" cellpadding="0" cellspacing="0">
        <tr> 
          <td class="featurenav" align="center" bgcolor="#3366CC"><strong>
          
          	<a href="AddSampler.jsp" class="featurenav"><font color="#FFFFFF">Add Sampler</font></a> | 
           <a href="AddWaterBody.jsp" class="featurenav"> <font color="#FFFFFF">Add Water Body</font></a>|
            <a href="UpdateContractor.jsp" class="featurenav" ><font color="#FFFFFF">Update Contractor</font></a> |
         	<a href="UpdateSampler.jsp" class="featurenav" >  <font color="#FFFFFF">Update Sampler</font></a> |
            <a href="UpdateWaterBody.jsp" class="featurenav"><font color="#FFFFFF">Update Water Body</font></a> |
           <a href="AssignSampler.jsp" class="featurenav"> <font color="#FFFFFF">Assign Sampler</font></a>|
            <a href="EnterSamplingFrequencies.jsp" class="featurenav"><font color="#FFFFFF">Enter Frequencies</font></a>|
           <a href="ManageExceedanceValues.jsp" class="featurenav" > <font color="#FFFFFF">Manage Exceedance</font></a> |
            <a href="SelectSamplingLocation.jsp" class="featurenav"><font color="#FFFFFF">Select Location</font></a> |
           <a href="PerformScreeningProgram.jsp" class="featurenav"> <font color="#FFFFFF">Perform Screening</font></a>|
            <a href="ScheduleSamplingFrequencies.jsp" class="featurenav"><font color="#FFFFFF">Schedule Frequencies</font></a>|
            <a href="CreateEnvironmentalAuditReport.jsp" class="featurenav"><font color="#FFFFFF">Create Environmental Report</font></a> |
           <a href="CreateExceedanceReport.jsp" class="featurenav"> <font color="#FFFFFF">Create Exceedance Report</font></a> |
            <a href="Glossary.jsp" class="featurenav"><font color="#FFFFFF">Glossary</font></a>|
           <a href="Definitions.jsp" class="featurenav"> <font color="#FFFFFF">Definitions</font></a>|   
           <a href="Keywords.jsp" class="featurenav"> <font color="#FFFFFF">Search</font></a>|                           
           </strong></td>
        </tr>
</table> 

</body>
